baseURL: https://gtil.github.io
languageCode: en-us
title: Grant Billings Homepage
theme: archie
copyright: © gtbil
pygmentsstyle: monokai
pygmentscodefences: yes
pygmentscodefencesguesssyntax: yes
params:
  mode: auto
  social:
    - icon: github
      name: GitHub
      url: https://github.com/gtbil/gtbil
    - icon: twitter
      name: Twitter
      url: https://twitter.com/athulcajay/
  subtitle: Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)
  useCDN: no
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: All posts
      url: /posts
      weight: 2
    - name: About
      url: /about
      weight: 3
    - name: Tags
      url: /tags
      weight: 4

markup:
  goldmark:
    renderer:
      unsafe: true
